# Generated by Django 5.1.5 on 2025-02-22 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineevent',
            name='year',
        ),
    ]
